### ISSUE TITLE
[ 已完成 ] [ 03-06-01-XDebug.md ] - [ 2015-03-05 ]

### ISSUE THREAD

**Issue by notech** [laravel-china/php-the-right-way#8]

**Comment by notech** [comment]
---

title:   Xdebug
isChild: true

## anchor:  notech

## Xdebug {#xdebug_title}

One of the most useful tools in software development is a proper debugger. It allows you to trace the execution of your
code and monitor the contents of the stack. Xdebug, PHP's debugger, can be utilized by various IDEs to provide
Breakpoints and stack inspection. It can also allow tools like PHPUnit and KCacheGrind to perform code coverage
analysis and code profiling.

合适的调试器是在软件开发中最有用的工具之一.它使你可以跟踪程序执行结果并监视程序堆栈中的信息.
Xdebug是一个php的调试器,它可以被用来在很多IDE(集成开发环境)中做断点调试以及堆栈检查.它还可以像
PHPUnit 和KCacheGrind一样 做代码覆盖检查或者程序性能跟踪.

If you find yourself in a bind, willing to resort to `var_dump()`/`print_r()`, and you still can't find the solution -
maybe you need to use the debugger.
如果你发现自己仍在使用 `var_dump()`/`print_r()`的手段并仍然无法解决问题的话或许你应该试试这个调试工具.

[Installing Xdebug](http://xdebug.org/docs/install) can be tricky, but one of its most important features is "Remote Debugging" - if
you develop code locally and then test it inside a VM or on another server, Remote Debugging is the feature that you
will want to enable right away.

[安装 Xdebug](http://xdebug.org/docs/install)可能很费事,但其中一个重要的特性"远程调试"- 如果你在本地开发但测试是在一台虚拟机或者其他服务器上的话,
远程调试可能是你想要的一种很好的方式.

Traditionally, you will modify your Apache VHost or .htaccess file with these values:

传统来讲,你可能需要修改你的Apache Vhost文件 或者 .htaccess文件:

{% highlight ini %}
php_value xdebug.remote_host=192.168.?.?
php_value xdebug.remote_port=9000
{% endhighlight %}

The "remote host" and "remote port" will correspond to your local computer and the port that you configure your IDE to
listen on. Then it's just a matter of putting your IDE into "listen for connections" mode, and loading the URL:
"remote host" 和 "remote port"这两项应该和你本地开发机监听的地址和端口一致.然后剩下的问题仅仅是将你的IDE设置成"listen for connections"模式并载入调试的URL:
    http://your-website.example.com/index.php?XDEBUG_SESSION_START=1

Your IDE will now intercept the current state as the script executes, allowing you to set breakpoints and probe the
values in memory.

Graphical debuggers make it very easy to step through code, inspect variables, and eval code against the live runtime.
Many IDE's have built-in or plugin-based support for graphical debugging with Xdebug. MacGDBp is a free, open-source,
stand-alone Xdebug GUI for Mac.
- [Learn more about Xdebug](http://xdebug.org/docs/)
- [Learn more about MacGDBp](http://www.bluestatic.org/software/macgdbp/)

**Comment by lifesign** [comment]
翻译完直接提Pull Request 即可不用放在这里。

**Comment by lution** [comment]
翻译的样式规范参考 README.md 里面给出的标准吧。你的中文标点好像都是用的半角符号，还有一些其他的细节最好也修改一下。
